name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  DOMAIN: checklaundry.com

jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Node deps
        working-directory: web
        run: yarn install

      - uses: pulumi/actions@v3
        with:
          work-dir: ./web
          command: up
          refresh: true
          stack-name: prod
          config-map: |
            {
              "cloud:provider": { value: "aws",                    secret: false },
              "aws:region": {     value: "${{ env.AWS_REGION }}",  secret: false },
              DOMAIN: {           value: "${{ env.DOMAIN }}",      secret: false },
              API_KEY: {          value: "${{ secrets.API_KEY }}", secret: true },
            }
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
